# Generated by Django 5.2.4 on 2026-02-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_emergency_request', to='blooddonorapp.hospital'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_staff', to='blooddonorapp.hospital'),
        ),
    ]
