# Generated by Django 5.2.4 on 2026-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('embedding_model', models.CharField(max_length=255)),
                ('llm_model', models.CharField(max_length=255)),
                ('chunk_size', models.IntegerField(default=1024)),
                ('chunk_overlap', models.IntegerField(default=128)),
                ('top_k', models.IntegerField(default=5)),
                ('version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('vectorstore_path', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
