# Generated by Django 5.2.4 on 2026-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonorapp', '0002_alter_emergencyrequest_hospital_alter_staff_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationevent',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
    ]
