# Generated by Django 5.2.4 on 2026-02-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonorapp', '0003_donationevent_is_expire_emergencyrequest_is_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationevent',
            name='is_expire',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='is_expire',
        ),
    ]
