# Generated by Django 5.2.4 on 2026-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonorapp', '0004_remove_donationevent_is_expire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationevent',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
    ]
