# Generated by Django 5.2.4 on 2026-02-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonorapp', '0005_donationevent_is_expire_emergencyrequest_is_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationevent',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='deadline_at',
        ),
    ]
